name: Build TS Clients and Examples
on:
  repository_dispatch:
    types: [build_publish_ts]

jobs:
  generate-ts:
    name: build TS clients and examples
    runs-on: ubuntu-latest
    steps:
      - name: Check m3o-js repo
        uses: actions/checkout@v3
        with:
          repository: m3o/m3o-js
          path: m3o-js

      - name: Check micro/services repo
        uses: actions/checkout@v3
        with:
          repository: 'micro/services'
          path: services

      - name: Generate m3o-js clients
        uses: m3o/m3o-generator-action@main
        with:
          target: 'ts'
          services_path: services

      - name: Adjust generated things before pushing
        working-directory: services
        
        run: |
          # sync the clients to m3o-js/
          rsync -avz clients/ts/ ../m3o-js/
          # sync the examples to m3o-js/examples
          rsync -avz examples/js/ ../m3o-js/examples/

      - name: update version number
        working-directory: m3o-js
        run: |
          oldver=$(cat package.json | grep version | head -1) 
          patch=$(echo $oldver | awk -F. '{ print $3}' | sed 's/"//g')
          newpatch=$(($patch+1))\" 
          seg1=$(echo $oldver | awk -F. '{ print $1}') 
          seg2=$(echo $oldver | awk -F. '{ print $2}') 
          newver="$seg1.$seg2.$newpatch" 
          sed -i "s/$oldver/$newver/" package.json
          echo "old $oldver"
          echo "new $newver"
          cat package.json

      - name: Push JS files
        uses: m3o/commit-action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'services/clients/ts/'
          destination_repo: 'GWT-M3O-TEST/m3o-js'
          destination_branch: 'main'
          github_server: 'github.com'
          user_name: 'lambdaR'
          use_rsync: true
          commit_message: 'Commit from generate-ts'

      - name: Publish m3o-js clients
        uses: m3o/m3o-publish-ts-action@main
        env:
          NPM_TOKEN: 'some random token'