name: M3O Client Generation Scheduler
on:
  push:
    branches:
      - main
      - beta
    paths:
      - '.github/workflows/scheduler.yml'
      - 'cmd/m3o-client-gen/**'
      - 'cmd/release-note/**'

  repository_dispatch:
    types: [build_m3o_client,build_dart,build_go,build_ts,build_shell,build_web]

jobs:
  disply-eventaction:
    runs-on: ubuntu-latest
    steps:
      - name: echo github.event.action
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}

  generate:
    if: ${{ github.event_name == 'push' || github.event.action == 'build_m3o_client' }}
    runs-on: ubuntu-latest
    steps:
      # - name: Trigger m3o/m3o-dart
      #   run: |
      #     curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-dart/dispatches -d '{"event_type":"build_publish_dart"}'
      #   env:
      #     GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}
      # - name: Trigger m3o/m3o-go
      #   run: |
      #     curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-go/dispatches -d '{"event_type":"build_publish_go"}'
      #   env:
      #     GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}
      # - name: Trigger m3o/m3o-ts
      #   run: |
      #     curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-ts/dispatches -d '{"event_type":"build_publish_ts"}'
      #   env:
      #     GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}
      # - name: Trigger m3o/m3o-sh
      #   run: |
      #     curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-sh/dispatches -d '{"event_type":"build_publish_shell"}'
      #   env:
      #     GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}
      # - name: Trigger m3o/m3o-cli
      #   run: |
      #     curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-cli/dispatches -d '{"event_type":"build_publish_cli"}'
      #   env:
      #     GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Trigger m3o/m3o-web
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-web/dispatches -d '{"event_type":"build_publish_web"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}

  generate-dart:
    if: ${{ github.event.action == 'build_dart' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger m3o/m3o-dart
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-dart/dispatches -d '{"event_type":"build_publish_dart"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}

  generate-go:
    if: ${{ github.event.action == 'build_go' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger m3o/m3o-go
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-go/dispatches -d '{"event_type":"build_publish_go"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}

  generate-ts:
    if: ${{ github.event.action == 'build_ts' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger m3o/m3o-ts
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-ts/dispatches -d '{"event_type":"build_publish_ts"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}

  generate-shell:
    if: ${{ github.event.action == 'build_shell' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger m3o/m3o-sh
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-sh/dispatches -d '{"event_type":"build_publish_shell"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}

  generate-web:
    if: ${{ github.event.action == 'build_web' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger m3o/m3o-web
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/GWT-m3o-web/dispatches -d '{"event_type":"build_publish_web"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}